#!/usr/bin/env python
"""Convert an old pydump stream into a json stream of events"""
import sys
from cStringIO import StringIO
import simplejson

def usage(e=None):
    if e:
        print >> sys.stderr, "error: " + str(e)
    print >> sys.stderr, "syntax: %s" % sys.argv[0]
    print >> sys.stderr, __doc__.strip()
    sys.exit(1)

def parse(fh):
    sio = StringIO()

    def fmt(sio):
        return sio.getvalue().strip()

    for line in fh.readlines():
        if line.startswith("{"):
            event = fmt(sio)
            if event:
                yield event
                sio.reset()
                sio.truncate()

        sio.write(line)

    yield fmt(sio)

def main():

    args = sys.argv[1:]
    if args and args[0] == '-h':
        usage()

    for event in parse(sys.stdin):
        event = eval(event)
        print simplejson.dumps(event, indent=True) + "\n"

if __name__ == "__main__":
    main()
