#!/usr/bin/perl -p

sub tagged {
    my $tag = shift;
    return /#$tag/i;
}

sub tag {
    foreach my $tag (@_) {
        if(!tagged $tag) {
            s/$/ #$tag/;
        }
    }
}

if(/ S=[LPEMSF]/) {
    /blog/i && tag blog;
    /security/i && tag security;

    if(/S=E/) {
        /review|plan/i && tag review;
        /email/i && tag email;
    }

} else {
    /plan|review/ && tag review;

    /\beat\b|meal|breakfast|brunch|lunch|dinner|snack|salad/i && tag meal;
    /breakfast/i && tag breakfast;
    /lunch|black rice/i && tag lunch;
    /dinner/i && tag dinner;

    /routine/ && tag routine;
    /morning/ && tag morning;
    /night/ && tag night;

    /procrast/ && tag procrast;
    /meditat/i && tag meditate;

    /rest|break(?!fast)|relax/ && tag relax;
    /read up|research|explore/ && tag research;
    /workout/ && !/pre|post/ && tag workout;

    /chat with/i && tag social;
    /cleanup/ && tag housework;

    /woke up.*back.*sleep/ && tag badsleep;
    /shower|shave/ && tag toilette;
    /reread|\bread(?! up|er)/ && tag 'read';
    
}

